language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - docker build --tag svn-server .
  - docker run --detach --publish 3690:3690 svn-server

script:
  - netstat -ln | grep 3690
